/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppGridItem {
    }
    interface AppProfileCard {
    }
    interface AppRoot {
    }
    interface AppShowcase {
    }
    interface AppSocialCard {
    }
    interface AppSummaryCard {
    }
}
declare global {
    interface HTMLAppGridItemElement extends Components.AppGridItem, HTMLStencilElement {
    }
    var HTMLAppGridItemElement: {
        prototype: HTMLAppGridItemElement;
        new (): HTMLAppGridItemElement;
    };
    interface HTMLAppProfileCardElement extends Components.AppProfileCard, HTMLStencilElement {
    }
    var HTMLAppProfileCardElement: {
        prototype: HTMLAppProfileCardElement;
        new (): HTMLAppProfileCardElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppShowcaseElement extends Components.AppShowcase, HTMLStencilElement {
    }
    var HTMLAppShowcaseElement: {
        prototype: HTMLAppShowcaseElement;
        new (): HTMLAppShowcaseElement;
    };
    interface HTMLAppSocialCardElement extends Components.AppSocialCard, HTMLStencilElement {
    }
    var HTMLAppSocialCardElement: {
        prototype: HTMLAppSocialCardElement;
        new (): HTMLAppSocialCardElement;
    };
    interface HTMLAppSummaryCardElement extends Components.AppSummaryCard, HTMLStencilElement {
    }
    var HTMLAppSummaryCardElement: {
        prototype: HTMLAppSummaryCardElement;
        new (): HTMLAppSummaryCardElement;
    };
    interface HTMLElementTagNameMap {
        "app-grid-item": HTMLAppGridItemElement;
        "app-profile-card": HTMLAppProfileCardElement;
        "app-root": HTMLAppRootElement;
        "app-showcase": HTMLAppShowcaseElement;
        "app-social-card": HTMLAppSocialCardElement;
        "app-summary-card": HTMLAppSummaryCardElement;
    }
}
declare namespace LocalJSX {
    interface AppGridItem {
    }
    interface AppProfileCard {
    }
    interface AppRoot {
    }
    interface AppShowcase {
    }
    interface AppSocialCard {
    }
    interface AppSummaryCard {
    }
    interface IntrinsicElements {
        "app-grid-item": AppGridItem;
        "app-profile-card": AppProfileCard;
        "app-root": AppRoot;
        "app-showcase": AppShowcase;
        "app-social-card": AppSocialCard;
        "app-summary-card": AppSummaryCard;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-grid-item": LocalJSX.AppGridItem & JSXBase.HTMLAttributes<HTMLAppGridItemElement>;
            "app-profile-card": LocalJSX.AppProfileCard & JSXBase.HTMLAttributes<HTMLAppProfileCardElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-showcase": LocalJSX.AppShowcase & JSXBase.HTMLAttributes<HTMLAppShowcaseElement>;
            "app-social-card": LocalJSX.AppSocialCard & JSXBase.HTMLAttributes<HTMLAppSocialCardElement>;
            "app-summary-card": LocalJSX.AppSummaryCard & JSXBase.HTMLAttributes<HTMLAppSummaryCardElement>;
        }
    }
}
